# Generated by Django 3.2.8 on 2021-10-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.CharField(max_length=200)),
                ('auxiliar', models.CharField(max_length=200)),
                ('bus', models.IntegerField()),
                ('respuesta', models.TextField()),
            ],
            options={
                'db_table': 'formulario',
                'managed': True,
            },
        ),
    ]
