# Generated by Django 3.2.8 on 2021-11-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_posturatabla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
