# Generated by Django 3.2.8 on 2021-11-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tabla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postura',
        ),
    ]
