# Generated by Django 3.2.8 on 2021-11-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_postura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosturaTabla',
        ),
    ]
