# Generated by Django 3.2.8 on 2021-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_posturatabla'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPostura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_principal', models.IntegerField()),
                ('id_conductor', models.IntegerField()),
                ('id_conductor2', models.IntegerField()),
                ('id_auxiliar', models.IntegerField()),
                ('bus_id', models.IntegerField()),
                ('conductor', models.CharField(max_length=200)),
                ('conductor2', models.CharField(max_length=200)),
                ('auxiliar', models.CharField(max_length=200)),
                ('bus', models.IntegerField()),
                ('respuesta', models.TextField()),
            ],
            options={
                'db_table': 'tablapostura',
                'managed': True,
            },
        ),
    ]
