# Generated by Django 3.2.8 on 2021-11-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tablapostura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla',
        ),
    ]
